# Generated by Django 3.2 on 2024-05-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=30, verbose_name='姓名')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='账号')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('gender', models.CharField(default='男', max_length=5, verbose_name='性别')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['username'],
            },
        ),
    ]
