# Generated by Django 3.2 on 2024-05-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seiden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='视频名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='视频描述')),
                ('duration', models.CharField(max_length=20, verbose_name='视频时长')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '视频信息',
                'verbose_name_plural': '视频信息',
                'ordering': ['-upload_time'],
            },
        ),
    ]
