# Generated by Django 3.2 on 2024-05-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seiden', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='D:/data/1.mp4', verbose_name='视频地址'),
            preserve_default=False,
        ),
    ]
