# Generated by Django 3.2 on 2024-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seiden', '0003_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='USER', max_length=10, verbose_name='角色'),
        ),
    ]
