# Generated by Django 3.2 on 2024-05-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seiden', '0004_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VdbmsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模型描述')),
                ('recommend', models.IntegerField(max_length=20, verbose_name='模型推荐度')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='模型上传时间')),
            ],
            options={
                'verbose_name': '模型信息',
                'verbose_name_plural': '模型信息',
            },
        ),
    ]
